@extends('layouts.app')

@section('content')

<div class="hero min-h-screen" style="background-image: url(https://images.pexels.com/photos/936048/pexels-photo-936048.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1);">
  <div class="hero-overlay bg-opacity-60"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-md">
      <h1 class="mb-5 text-5xl font-bold">Laravel on Vercel</h1>
      <p class="mb-5">The error message you're encountering suggests that the autoload.php file, which is typically located in the vendor directory, is missing or cannot be found. This file is generated by Composer, a dependency management tool for PHP projects.</p>
      <button class="btn btn-primary">Get Started</button>
    </div>
  </div>
</div>
@endsection
